---
extends: default

rules:
  braces:
    # Defaults
    # min-spaces-inside:    0
    # max-spaces-inside:    0

    # Keeping 0 min-spaces to not error on empty collection definitions
    min-spaces-inside: 0
    # Allowing one space inside braces to improve code readability
    max-spaces-inside: 1

  brackets:
    # Defaults
    # min-spaces-inside:    0
    # max-spaces-inside:    0

    # Keeping 0 min-spaces to not error on empty collection definitions
    min-spaces-inside: 0
    # Allowing one space inside braces to improve code readability
    max-spaces-inside: 1

  colons:
    # Defaults
    # max-spaces-before:    0
    # max-spaces-after:     1

    max-spaces-before: 0
    # Allowing more than one space for code readability
    max-spaces-after: -1

  comments:
    # Defaults
    # level:                warning
    # require-starting-space: true
    # min-spaces-from-content: 2

    # Disabling to allow for code comment blocks and #!/usr/bin/ansible-playbook
    require-starting-space: false

  indentation:
    # Defaults
    # spaces:               consistent
    # indent-sequences:     true
    # check-multi-line-strings: false

    # Requiring 2 space indentation
    spaces: 2
    # Requiring consistent indentation within a file, either indented or not
    indent-sequences: consistent

  # Disabling due to copious amounts of long lines in the code which would
  # require a code style change to resolve
  line-length: disable

  truthy: disable
