---
- name: Debian | Updating Apt-Cache
  apt:
    update_cache: true
    cache_valid_time: 86400

- name: Debian | Installing Pre-Reqs
  apt:
    name: "{{ item }}"
    state: "present"
  with_items:
    - 'git'
    - 'libffi-dev'
    - 'libssl-dev'
    - 'python-dev'
    - 'python-setuptools'
    - 'sshpass'
    - 'tree'

- name: Debian | Installing Python-Pip
  apt:
    name: "python-pip"
    state: "present"
  when: not easy_install_pip
