---
- name: RedHat | Installing EPEL Repo (RedHat)
  yum:
    name: epel-release
    state: present
  become: true
  register: result
  until: result is successful
  when: >
    ansible_distribution != "Fedora"

- name: RedHat | Installing Pre-Reqs (RedHat)
  yum:
    name:
      [
        "git",
        "libffi-devel",
        "openssl-devel",
        "python-crypto",
        "python-devel",
        "python-setuptools",
      ]
    state: present
  become: true
  register: result
  until: result is successful
  when: >
    ansible_distribution != "Fedora"

- name: RedHat | Installing Pre-Reqs (Fedora)
  dnf:
    name:
      [
        "git",
        "gmp-devel",
        "libffi-devel",
        "openssl-devel",
        "python-crypto",
        "python-devel",
        "python-dnf",
        "python-setuptools",
        "redhat-rpm-config",
      ]
    state: "present"
  become: true
  register: result
  until: result is successful
  when: >
    ansible_distribution == "Fedora"

- name: RedHat | Installing Python-Pip
  yum:
    name: python-pip
    state: present
  become: true
  register: result
  until: result is successful
  when: >
    not easy_install_pip and
    ansible_distribution != "Fedora"

- name: RedHat | Installing Python-Pip
  dnf:
    name: python-pip
    state: present
  become: true
  register: result
  until: result is successful
  when: >
    not easy_install_pip and
    ansible_distribution == "Fedora"
