---
# Need to add EPEL Repo for python2 pip
- name: redhat | Adding EPEL Repo
  yum:
    name: epel-release
    state: present
  become: true
  register: result
  until: result is successful
  when:
    - ansible_distribution != "Fedora"
    - ansible_python_version is version('3', '<')

- name: RedHat | Installing Pre-Reqs (RedHat)
  yum:
    name: "{{ control_machine_pre_req_packages }}"
    state: present
  become: true
  register: result
  until: result is successful
  when:
    - ansible_distribution != "Fedora"

- name: RedHat | Installing Pre-Reqs (Fedora)
  dnf:
    name: "{{ control_machine_pre_req_packages }}"
    state: present
  become: true
  register: result
  until: result is successful
  when:
    - ansible_distribution == "Fedora"
