---
- name: setup | Installing Python Pip
  easy_install:
    name: pip
    state: present
  become: true
  when: easy_install_pip|bool

- name: setup | Installing Python Virtualenv Packages
  pip:
    name: ["httplib2", "virtualenv"]
    state: "present"
  become: true

- name: setup | Configuring Ansible Virtual Environments
  pip:
    name: ansible
    version: "{{ item.ver |default (omit) }}"
    virtualenv: "{{ ansible_virtualenv_dir }}/{{ item.ver }}"
  become: true
  with_items: "{{ ansible_versions }}"

- name: setup | Installing Additional Python Modules in Ansible Virtual Environments
  pip:
    name: "{{ item.1 }}"
    state: present
    virtualenv: "{{ ansible_virtualenv_dir }}/{{ item.0.ver }}"
  become: true
  with_subelements:
    - "{{ ansible_versions }}"
    - addl_modules
  when: >
    item.1 is defined and
    item.1 != 'None'

- name: setup | Ensuring Ansible Roles Directory Exists {{ ansible_roles_dir }}
  file:
    path: "{{ ansible_roles_dir }}"
    state: directory
  become: true
  when: clone_ansible_roles|bool

- name: setup | Cloning Ansible Repos to {{ ansible_roles_dir }}
  git:
    repo: "{{ item.repo }}"
    dest: "{{ ansible_roles_dir }}/{{ item.dest }}"
  with_items: "{{ ansible_roles }}"
  when: clone_ansible_roles

- name: setup | Ensuring Ansible Playbooks Directory Exists {{ ansible_playbooks_dir }}
  file:
    path: "{{ ansible_playbooks_dir }}"
    state: directory
  become: true

- name: setup | Cloning Ansible Playbook Repos to {{ ansible_playbooks_dir }}
  git:
    repo: "{{ item.repo }}"
    dest: "{{ ansible_playbooks_dir }}/{{ item.dest }}"
  with_items: "{{ ansible_playbooks }}"

- name: setup | How-To
  debug:
    msg: >
      To use Ansible Virtual Environments...
      SSH to Ansible Control Machine...
      source the desired Ansible version as...  ex.
      source {{ ansible_virtualenv_dir }}/2.1.0.0/bin/activate
