---
- name: setup | Creating Virtual Environments and Updating Important Libs # noqa 403
  pip:
    name:
      - pip
      - cffi
      - pyOpenSSL
    state: latest
    virtualenv: "{{ control_machine_virtualenv_dir+'/'+item['ver']|string }}"
  become: true
  register: result
  until: result is successful
  loop: "{{ control_machine_ansible_versions }}"

- name: setup | Installing Ansible In Virtual Environments
  pip:
    name: ansible
    version: "{{ item['ver'] }}"
    virtualenv: "{{ control_machine_virtualenv_dir+'/'+item['ver']|string }}"
  become: true
  register: result
  until: result is successful
  loop: "{{ control_machine_ansible_versions }}"

- name: setup | Installing Add'l Python Libs in Ansible Virtual Environments
  pip:
    name: "{{ item[1]['name'] }}"
    state: "{{ item[1]['state']|default('present') }}"
    virtualenv: "{{ control_machine_virtualenv_dir+'/'+item[0]['ver']|string }}"
  become: true
  loop: "{{ lookup('subelements', control_machine_ansible_versions, 'addl_modules', {'skip_missing': True}, wantlist=True) }}"

- name: setup | Ensuring Ansible Roles Directory Exists {{ control_machine_roles_dir }}
  file:
    path: "{{ control_machine_roles_dir }}"
    state: directory
  become: true
  when: control_machine_clone_roles|bool

- name: setup | Cloning Ansible Repos to {{ control_machine_roles_dir }} # noqa 401
  git:
    repo: "{{ item['repo'] }}"
    dest: "{{ control_machine_roles_dir+'/'+item['dest'] }}"
  become: true
  loop: "{{ control_machine_roles }}"
  when: control_machine_clone_roles|bool

- name: setup | Ensuring Ansible Playbooks Directory Exists {{ control_machine_playbooks_dir }}
  file:
    path: "{{ control_machine_playbooks_dir }}"
    state: directory
  become: true

- name: setup | Cloning Ansible Playbook Repos to {{ control_machine_playbooks_dir }} # noqa 401
  git:
    repo: "{{ item['repo'] }}"
    dest: "{{ control_machine_playbooks_dir+'/'+item['dest'] }}"
  become: true
  loop: "{{ control_machine_playbooks }}"

- name: setup | How-To
  debug:
    msg: >
      To use Ansible Virtual Environments...
      SSH to Ansible Control Machine...
      source the desired Ansible version as...  ex.
      source {{ control_machine_virtualenv_dir }}/2.9.5/bin/activate
